In [16]:
import os
os.chdir(r'D:\Assignment2_40156103')


In [17]:
pwd

'D:\\Assignment2_40156103'

In [18]:
import numpy as np
import pandas as pd
#directory = r'C:\Users\fionn\OneDrive\Documents\Assignment2_40156103\UlFl0FinFmKZlHd (1)'
directory = r'./UlFl0FinFmKZlHd (1)'
npfeatures_file = np.array([70,8,32,14,12,1,8,5,2,1,1,15,11,8,11,12,1,0,1,0,0,0])
filelist = []


for root, dirs, files in os.walk(directory):
    for file in files:
        if 'features.csv' in file:
            filename = directory + "\\" + file
            b = np.loadtxt(filename, delimiter = ',', dtype = int)
            npfeatures_file = np.vstack((npfeatures_file, b ))
    npfeatures_file = np.delete(npfeatures_file, 0, 0) 
print(npfeatures_file)
            

[[11  8 32 ...  0  0  0]
 [11  3 39 ...  0  0  0]
 [11  4 26 ...  0  0  0]
 ...
 [37  4 34 ...  0  0  0]
 [37  1 32 ...  0  0  0]
 [37  6 34 ...  0  0  0]]


In [20]:
df = pd.DataFrame(npfeatures_file)
os.chdir(r'./features')
df.to_csv("trainingfeatures.csv", index = False, header = False )